name: dynamic_array CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: compile
      run: gcc --std=c99 *.c -o main
    - name: clean
      run: rm ./main
